apiVersion: v1
kind: Secret
metadata:
  name: tvbo-postgres-db-credentials
  namespace: kube-system
stringData:
  POSTGRES_DB: tvbo_postgres
  POSTGRES_USER: tvbo_odoo
  POSTGRES_PASSWORD: odoo  # Change in production!

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvbo-postgres-pvc
  namespace: kube-system
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: tvbo-odoo-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: Service
metadata:
  name: tvbo-postgres
  namespace: kube-system
spec:
  selector:
    app: tvbo-postgres
  ports: [{port: 5432}]

---
apiVersion: v1
kind: Service
metadata:
  name: tvbo-api
  namespace: kube-system
spec:
  selector:
    app: tvbo-api
  ports: [{port: 8000}]



---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: kube-system
spec:
  selector:
    app: odoo
  ports: [{port: 8069}]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvbo-odoo
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tvbo-odoo
  template:
    metadata:
      labels:
        app: tvbo-odoo
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: tvbo-odoo
          image: ghcr.io/leon-k-martin/tvbo-platform:main
          ports: [{containerPort: 8069}]
          env:
            - {name: HOST, value: tvbo-postgres}
            - {name: USER, value: tvbo_odoo}
            - {name: PASSWORD, value: odoo}
          volumeMounts: [{name: data, mountPath: /var/lib/odoo}]
          readinessProbe:
            httpGet: {path: /web/health, port: 8069}
            initialDelaySeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tvbo-odoo-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvbo-api
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tvbo-api
  template:
    metadata:
      labels:
        app: tvbo-api
    spec:
      imagePullSecrets:
        - name: github-credentials
      containers:
        - name: tvbo-api
          image: leonmartin2/tvbo:dev
          ports: [{containerPort: 8000}]
          env: [{name: MODE, value: api}]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvbo-postgres
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tvbo-postgres
  template:
    metadata:
      labels:
        app: tvbo-postgres
    spec:
      containers:
        - name: tvbo-postgres
          image: postgres:17
          ports: [{containerPort: 5432}]
          envFrom: [{secretRef: {name: tvbo-postgres-db-credentials}}]
          volumeMounts: [{name: data, mountPath: /var/lib/postgresql/data}]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tvbo-postgres-pvc

---
