from . import assets
from . import main
from . import model_configurator
from . import portal
from . import api
from . import schema_api
from . import kg_api
from . import document_parser
from . import building_blocks_api
from . import forum
